### ISSUE TITLE
Setup Failed after EVER Trasnfer

### ISSUE THREAD

**Issue by TusharPardhe** [EvernodeXRPL/evernode-host#361]
<img width="1388" alt="Screenshot 2024-03-16 at 12 21 49 pm" src="https://github.com/EvernodeXRPL/evernode-host/assets/31487192/7ee3b13f-7a6e-4612-a420-47bf91283991">

2024-03-16 12:35:51 ---Sashimono prerequisites installer---
2024-03-16 12:35:51 STAGE Installing dependencies
2024-03-16 12:35:51 Hit:1 https://mirror.hetzner.com/ubuntu/packages focal InRelease
2024-03-16 12:35:51 Hit:2 https://mirror.hetzner.com/ubuntu/packages focal-updates InRelease
2024-03-16 12:35:51 Hit:3 https://mirror.hetzner.com/ubuntu/packages focal-backports InRelease
2024-03-16 12:35:51 Hit:4 https://mirror.hetzner.com/ubuntu/security focal-security InRelease
2024-03-16 12:35:51 Hit:5 https://deb.nodesource.com/node_20.x nodistro InRelease
2024-03-16 12:35:53 Reading package lists...
2024-03-16 12:35:53 Reading package lists...
2024-03-16 12:35:53 Building dependency tree...
2024-03-16 12:35:53 Reading state information...
2024-03-16 12:35:54 quota is already the newest version (4.05-1).
2024-03-16 12:35:54 cgroup-tools is already the newest version (0.41-10).
2024-03-16 12:35:54 fuse3 is already the newest version (3.9.0-2).
2024-03-16 12:35:54 curl is already the newest version (7.68.0-1ubuntu2.21).
2024-03-16 12:35:54 openssl is already the newest version (1.1.1f-1ubuntu2.22).
2024-03-16 12:35:54 uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.5).
2024-03-16 12:35:54 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2024-03-16 12:35:54 STAGE Configuring fstab
2024-03-16 12:35:54 fstab already configured.
2024-03-16 12:35:54 STAGE Configuring fuse
2024-03-16 12:35:54 Fuse config already updated.
2024-03-16 12:35:54 STAGE Configuring cgroup rules engine
2024-03-16 12:35:54 STAGE Configuring grub
2024-03-16 12:35:54 Grub already configured.
2024-03-16 12:35:56 ---Sashimono installer---
2024-03-16 12:35:56 [STAGE] Setting up letsencrypt certbot
2024-03-16 12:35:58 Skipping adding existing rule
2024-03-16 12:35:58 Skipping adding existing rule (v6)
2024-03-16 12:35:58 Running certbot certonly
2024-03-16 12:35:58 Attempting command [certbot certonly -n -d tusharever.co --agree-tos --email tusharever@proton.me --standalone] (attempt 1/3)
2024-03-16 12:36:03 Saving debug log to /var/log/letsencrypt/letsencrypt.log
2024-03-16 12:36:04 Requesting a certificate for tusharever.co
2024-03-16 12:36:04 
2024-03-16 12:36:04 Successfully received certificate.
2024-03-16 12:36:04 Certificate is saved at: /etc/letsencrypt/live/tusharever.co/fullchain.pem
2024-03-16 12:36:04 Key is saved at:         /etc/letsencrypt/live/tusharever.co/privkey.pem
2024-03-16 12:36:04 This certificate expires on 2024-06-14.
2024-03-16 12:36:04 These files will be updated when the certificate renews.
2024-03-16 12:36:04 Certbot has set up a scheduled task to automatically renew this certificate in the background.
2024-03-16 12:36:04 
2024-03-16 12:36:04 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2024-03-16 12:36:04 If you like Certbot, please consider supporting our work by:
2024-03-16 12:36:04  * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
2024-03-16 12:36:04  * Donating to EFF:                    https://eff.org/donate-le
2024-03-16 12:36:04 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2024-03-16 12:36:04 Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-tusharever.co.sh
2024-03-16 12:36:04 [STAGE] Installing docker packages
2024-03-16 12:36:04 Private docker registry installation skipped
2024-03-16 12:36:04 Configuaring host setup on Evernode...
2024-03-16 12:36:04 [STAGE] Configuring host Xahau account
2024-03-16 12:36:04 Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
2024-03-16 12:36:04 Unhandled exception occurred: /usr/bin/sashimono/mb-xrpl/lib/binding/napi-v3-linux-x64/node_sqlite3.node: cannot open shared object file: No such file or directory
2024-03-16 12:36:04 Stack trace: Error: /usr/bin/sashimono/mb-xrpl/lib/binding/napi-v3-linux-x64/node_sqlite3.node: cannot open shared object file: No such file or directory
2024-03-16 12:36:04     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
2024-03-16 12:36:04     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-16 12:36:04     at Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-16 12:36:04     at Module.require (node:internal/modules/cjs/loader:1235:19)
2024-03-16 12:36:04     at require (node:internal/modules/helpers:176:18)
2024-03-16 12:36:04     at 1449 (/usr/bin/sashimono/mb-xrpl/index.js:1:1622)
2024-03-16 12:36:04     at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:64:473730)
2024-03-16 12:36:04     at 4400 (/usr/bin/sashimono/mb-xrpl/index.js:64:3848)
2024-03-16 12:36:04     at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:64:473730)
2024-03-16 12:36:04     at 2173 (/usr/bin/sashimono/mb-xrpl/index.js:64:3909)
2024-03-16 12:36:04 MB_CLI_EXITED
2024-03-16 12:36:04 CONFIG_SAVING_FAILURE

**Comment by TusharPardhe** [comment]
I have tried reinstall setup twice, same error.

**Comment by TusharPardhe** [comment]
There was some architecture issue with AMD
