### ISSUE TITLE
sashimono reputationd  fail

### ISSUE THREAD

**Issue by Zamolxis969** [EvernodeXRPL/evernode-host#411]
sudo -u sashireputationd bash -c 'journalctl --user -u sashimono-reputationd | tail -n 250'
Sep 01 09:01:38 ivy1 node[3743]: 20240901 14:01:38 [dbg] Checking IPV4 support...
Sep 01 09:01:38 ivy1 node[3743]: 20240901 14:01:38 [dbg] Checking version compatibility...
Sep 01 09:01:38 ivy1 node[3743]: 20240901 14:01:38 [dbg] Checking SSL certificate validity...
Sep 01 09:01:38 ivy1 node[3743]: 20240901 14:01:38 [dbg] All requirement checks passed.
Sep 01 09:01:38 ivy1 node[3743]: 20240901 14:01:38 [err] RippledError: Invalid parameters.
Sep 01 09:01:38 ivy1 node[3743]:     at RequestManager.handleResponse (/usr/bin/sashimono/reputationd/index.js:59:91027)
Sep 01 09:01:38 ivy1 node[3743]:     at Connection.onMessage (/usr/bin/sashimono/reputationd/index.js:59:96558)
Sep 01 09:01:38 ivy1 node[3743]:     at WebSocket.<anonymous> (/usr/bin/sashimono/reputationd/index.js:59:97000)
Sep 01 09:01:38 ivy1 node[3743]:     at WebSocket.emit (node:events:519:28)
Sep 01 09:01:38 ivy1 node[3743]:     at Receiver.receiverOnMessage (/usr/bin/sashimono/reputationd/index.js:59:75763)
Sep 01 09:01:38 ivy1 node[3743]:     at Receiver.emit (node:events:519:28)
Sep 01 09:01:38 ivy1 node[3743]:     at Receiver.dataMessage (/usr/bin/sashimono/reputationd/index.js:59:46441)
Sep 01 09:01:38 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:45652
Sep 01 09:01:38 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:37708
Sep 01 09:01:38 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:38659 {
Sep 01 09:01:38 ivy1 node[3743]:   data: {
Sep 01 09:01:38 ivy1 node[3743]:     error: 'invalidParams',
Sep 01 09:01:38 ivy1 node[3743]:     error_code: 31,
Sep 01 09:01:38 ivy1 node[3743]:     error_message: 'Invalid parameters.',
Sep 01 09:01:38 ivy1 node[3743]:     id: 999,
Sep 01 09:01:38 ivy1 node[3743]:     request: {
Sep 01 09:01:38 ivy1 node[3743]:       account: 'raYDnpvfRTtAQhi9BeidowAcU8NtcFVbvt',
Sep 01 09:01:38 ivy1 node[3743]:       command: 'account_lines',
Sep 01 09:01:38 ivy1 node[3743]:       id: 999,
Sep 01 09:01:38 ivy1 node[3743]:       ledger_index: 'validated',
Sep 01 09:01:38 ivy1 node[3743]:       limit: 400,
Sep 01 09:01:38 ivy1 node[3743]:       marker: '379DD0DB375CA48E55281FDCB9B7C40A7FF9CD53B50CE94AF087634B978C5C54,276',
Sep 01 09:01:38 ivy1 node[3743]:       peer: 'rEvernodee8dJLaFsujS6q1EiXvZYmHXr8'
Sep 01 09:01:38 ivy1 node[3743]:     },
Sep 01 09:01:38 ivy1 node[3743]:     status: 'error',
Sep 01 09:01:38 ivy1 node[3743]:     type: 'response'
Sep 01 09:01:38 ivy1 node[3743]:   }
Sep 01 09:01:38 ivy1 node[3743]: }
Sep 01 09:01:38 ivy1 node[3743]: 20240901 14:01:38 [dbg] Retry attempt 1
Sep 01 09:06:39 ivy1 node[3743]: 20240901 14:06:39 [err] RippledError: Invalid parameters.
Sep 01 09:06:39 ivy1 node[3743]:     at RequestManager.handleResponse (/usr/bin/sashimono/reputationd/index.js:59:91027)
Sep 01 09:06:39 ivy1 node[3743]:     at Connection.onMessage (/usr/bin/sashimono/reputationd/index.js:59:96558)
Sep 01 09:06:39 ivy1 node[3743]:     at WebSocket.<anonymous> (/usr/bin/sashimono/reputationd/index.js:59:97000)
Sep 01 09:06:39 ivy1 node[3743]:     at WebSocket.emit (node:events:519:28)
Sep 01 09:06:39 ivy1 node[3743]:     at Receiver.receiverOnMessage (/usr/bin/sashimono/reputationd/index.js:59:75763)
Sep 01 09:06:39 ivy1 node[3743]:     at Receiver.emit (node:events:519:28)
Sep 01 09:06:39 ivy1 node[3743]:     at Receiver.dataMessage (/usr/bin/sashimono/reputationd/index.js:59:46441)
Sep 01 09:06:39 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:45652
Sep 01 09:06:39 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:37708
Sep 01 09:06:39 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:38659 {
Sep 01 09:06:39 ivy1 node[3743]:   data: {
Sep 01 09:06:39 ivy1 node[3743]:     error: 'invalidParams',
Sep 01 09:06:39 ivy1 node[3743]:     error_code: 31,
Sep 01 09:06:39 ivy1 node[3743]:     error_message: 'Invalid parameters.',
Sep 01 09:06:39 ivy1 node[3743]:     id: 1020,
Sep 01 09:06:39 ivy1 node[3743]:     request: {
Sep 01 09:06:39 ivy1 node[3743]:       account: 'raYDnpvfRTtAQhi9BeidowAcU8NtcFVbvt',
Sep 01 09:06:39 ivy1 node[3743]:       command: 'account_lines',
Sep 01 09:06:39 ivy1 node[3743]:       id: 1020,
Sep 01 09:06:39 ivy1 node[3743]:       ledger_index: 'validated',
Sep 01 09:06:39 ivy1 node[3743]:       limit: 400,
Sep 01 09:06:39 ivy1 node[3743]:       marker: '379DD0DB375CA48E55281FDCB9B7C40A7FF9CD53B50CE94AF087634B978C5C54,276',
Sep 01 09:06:39 ivy1 node[3743]:       peer: 'rEvernodee8dJLaFsujS6q1EiXvZYmHXr8'
Sep 01 09:06:39 ivy1 node[3743]:     },
Sep 01 09:06:39 ivy1 node[3743]:     status: 'error',
Sep 01 09:06:39 ivy1 node[3743]:     type: 'response'
Sep 01 09:06:39 ivy1 node[3743]:   }
Sep 01 09:06:39 ivy1 node[3743]: }
Sep 01 09:06:39 ivy1 node[3743]: 20240901 14:06:39 [dbg] Retry attempt 2
Sep 01 09:11:39 ivy1 node[3743]: 20240901 14:11:39 [err] RippledError: Invalid parameters.
Sep 01 09:11:39 ivy1 node[3743]:     at RequestManager.handleResponse (/usr/bin/sashimono/reputationd/index.js:59:91027)
Sep 01 09:11:39 ivy1 node[3743]:     at Connection.onMessage (/usr/bin/sashimono/reputationd/index.js:59:96558)
Sep 01 09:11:39 ivy1 node[3743]:     at WebSocket.<anonymous> (/usr/bin/sashimono/reputationd/index.js:59:97000)
Sep 01 09:11:39 ivy1 node[3743]:     at WebSocket.emit (node:events:519:28)
Sep 01 09:11:39 ivy1 node[3743]:     at Receiver.receiverOnMessage (/usr/bin/sashimono/reputationd/index.js:59:75763)
Sep 01 09:11:39 ivy1 node[3743]:     at Receiver.emit (node:events:519:28)
Sep 01 09:11:39 ivy1 node[3743]:     at Receiver.dataMessage (/usr/bin/sashimono/reputationd/index.js:59:46441)
Sep 01 09:11:39 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:45652
Sep 01 09:11:39 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:37708
Sep 01 09:11:39 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:38659 {
Sep 01 09:11:39 ivy1 node[3743]:   data: {
Sep 01 09:11:39 ivy1 node[3743]:     error: 'invalidParams',
Sep 01 09:11:39 ivy1 node[3743]:     error_code: 31,
Sep 01 09:11:39 ivy1 node[3743]:     error_message: 'Invalid parameters.',
Sep 01 09:11:39 ivy1 node[3743]:     id: 1041,
Sep 01 09:11:39 ivy1 node[3743]:     request: {
Sep 01 09:11:39 ivy1 node[3743]:       account: 'raYDnpvfRTtAQhi9BeidowAcU8NtcFVbvt',
Sep 01 09:11:39 ivy1 node[3743]:       command: 'account_lines',
Sep 01 09:11:39 ivy1 node[3743]:       id: 1041,
Sep 01 09:11:39 ivy1 node[3743]:       ledger_index: 'validated',
Sep 01 09:11:39 ivy1 node[3743]:       limit: 400,
Sep 01 09:11:39 ivy1 node[3743]:       marker: '379DD0DB375CA48E55281FDCB9B7C40A7FF9CD53B50CE94AF087634B978C5C54,276',
Sep 01 09:11:39 ivy1 node[3743]:       peer: 'rEvernodee8dJLaFsujS6q1EiXvZYmHXr8'
Sep 01 09:11:39 ivy1 node[3743]:     },
Sep 01 09:11:39 ivy1 node[3743]:     status: 'error',
Sep 01 09:11:39 ivy1 node[3743]:     type: 'response'
Sep 01 09:11:39 ivy1 node[3743]:   }
Sep 01 09:11:39 ivy1 node[3743]: }
Sep 01 09:11:39 ivy1 node[3743]: 20240901 14:11:39 [dbg] Retry attempt 3
Sep 01 09:16:27 ivy1 node[3743]: 20240901 14:16:27 [dbg] Skipping reputation contract preparation since there's no universe info for the moment 6297.
Sep 01 09:16:40 ivy1 node[3743]: 20240901 14:16:40 [err] RippledError: Invalid parameters.
Sep 01 09:16:40 ivy1 node[3743]:     at RequestManager.handleResponse (/usr/bin/sashimono/reputationd/index.js:59:91027)
Sep 01 09:16:40 ivy1 node[3743]:     at Connection.onMessage (/usr/bin/sashimono/reputationd/index.js:59:96558)
Sep 01 09:16:40 ivy1 node[3743]:     at WebSocket.<anonymous> (/usr/bin/sashimono/reputationd/index.js:59:97000)
Sep 01 09:16:40 ivy1 node[3743]:     at WebSocket.emit (node:events:519:28)
Sep 01 09:16:40 ivy1 node[3743]:     at Receiver.receiverOnMessage (/usr/bin/sashimono/reputationd/index.js:59:75763)
Sep 01 09:16:40 ivy1 node[3743]:     at Receiver.emit (node:events:519:28)
Sep 01 09:16:40 ivy1 node[3743]:     at Receiver.dataMessage (/usr/bin/sashimono/reputationd/index.js:59:46441)
Sep 01 09:16:40 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:45652
Sep 01 09:16:40 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:37708
Sep 01 09:16:40 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:38659 {
Sep 01 09:16:40 ivy1 node[3743]:   data: {
Sep 01 09:16:40 ivy1 node[3743]:     error: 'invalidParams',
Sep 01 09:16:40 ivy1 node[3743]:     error_code: 31,
Sep 01 09:16:40 ivy1 node[3743]:     error_message: 'Invalid parameters.',
Sep 01 09:16:40 ivy1 node[3743]:     id: 1063,
Sep 01 09:16:40 ivy1 node[3743]:     request: {
Sep 01 09:16:40 ivy1 node[3743]:       account: 'raYDnpvfRTtAQhi9BeidowAcU8NtcFVbvt',
Sep 01 09:16:40 ivy1 node[3743]:       command: 'account_lines',
Sep 01 09:16:40 ivy1 node[3743]:       id: 1063,
Sep 01 09:16:40 ivy1 node[3743]:       ledger_index: 'validated',
Sep 01 09:16:40 ivy1 node[3743]:       limit: 400,
Sep 01 09:16:40 ivy1 node[3743]:       marker: '379DD0DB375CA48E55281FDCB9B7C40A7FF9CD53B50CE94AF087634B978C5C54,276',
Sep 01 09:16:40 ivy1 node[3743]:       peer: 'rEvernodee8dJLaFsujS6q1EiXvZYmHXr8'
Sep 01 09:16:40 ivy1 node[3743]:     },
Sep 01 09:16:40 ivy1 node[3743]:     status: 'error',
Sep 01 09:16:40 ivy1 node[3743]:     type: 'response'
Sep 01 09:16:40 ivy1 node[3743]:   }
Sep 01 09:16:40 ivy1 node[3743]: }
Sep 01 09:16:40 ivy1 node[3743]: 20240901 14:16:40 [err] Max retry attempts reached. Abandoned.
Sep 01 10:01:38 ivy1 node[3743]: 20240901 15:01:38 [dbg] Checking IPV4 support...
Sep 01 10:01:38 ivy1 node[3743]: 20240901 15:01:38 [dbg] Checking version compatibility...
Sep 01 10:01:38 ivy1 node[3743]: 20240901 15:01:38 [dbg] Checking SSL certificate validity...
Sep 01 10:01:38 ivy1 node[3743]: 20240901 15:01:38 [dbg] All requirement checks passed.
Sep 01 10:01:39 ivy1 node[3743]: 20240901 15:01:39 [err] RippledError: Invalid parameters.
Sep 01 10:01:39 ivy1 node[3743]:     at RequestManager.handleResponse (/usr/bin/sashimono/reputationd/index.js:59:91027)
Sep 01 10:01:39 ivy1 node[3743]:     at Connection.onMessage (/usr/bin/sashimono/reputationd/index.js:59:96558)
Sep 01 10:01:39 ivy1 node[3743]:     at WebSocket.<anonymous> (/usr/bin/sashimono/reputationd/index.js:59:97000)
Sep 01 10:01:39 ivy1 node[3743]:     at WebSocket.emit (node:events:519:28)
Sep 01 10:01:39 ivy1 node[3743]:     at Receiver.receiverOnMessage (/usr/bin/sashimono/reputationd/index.js:59:75763)
Sep 01 10:01:39 ivy1 node[3743]:     at Receiver.emit (node:events:519:28)
Sep 01 10:01:39 ivy1 node[3743]:     at Receiver.dataMessage (/usr/bin/sashimono/reputationd/index.js:59:46441)
Sep 01 10:01:39 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:45652
Sep 01 10:01:39 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:37708
Sep 01 10:01:39 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:38659 {
Sep 01 10:01:39 ivy1 node[3743]:   data: {
Sep 01 10:01:39 ivy1 node[3743]:     error: 'invalidParams',
Sep 01 10:01:39 ivy1 node[3743]:     error_code: 31,
Sep 01 10:01:39 ivy1 node[3743]:     error_message: 'Invalid parameters.',
Sep 01 10:01:39 ivy1 node[3743]:     id: 1204,
Sep 01 10:01:39 ivy1 node[3743]:     request: {
Sep 01 10:01:39 ivy1 node[3743]:       account: 'raYDnpvfRTtAQhi9BeidowAcU8NtcFVbvt',
Sep 01 10:01:39 ivy1 node[3743]:       command: 'account_lines',
Sep 01 10:01:39 ivy1 node[3743]:       id: 1204,
Sep 01 10:01:39 ivy1 node[3743]:       ledger_index: 'validated',
Sep 01 10:01:39 ivy1 node[3743]:       limit: 400,
Sep 01 10:01:39 ivy1 node[3743]:       marker: '379DD0DB375CA48E55281FDCB9B7C40A7FF9CD53B50CE94AF087634B978C5C54,276',
Sep 01 10:01:39 ivy1 node[3743]:       peer: 'rEvernodee8dJLaFsujS6q1EiXvZYmHXr8'
Sep 01 10:01:39 ivy1 node[3743]:     },
Sep 01 10:01:39 ivy1 node[3743]:     status: 'error',
Sep 01 10:01:39 ivy1 node[3743]:     type: 'response'
Sep 01 10:01:39 ivy1 node[3743]:   }
Sep 01 10:01:39 ivy1 node[3743]: }
Sep 01 10:01:39 ivy1 node[3743]: 20240901 15:01:39 [dbg] Retry attempt 1
Sep 01 10:06:40 ivy1 node[3743]: 20240901 15:06:40 [err] RippledError: Invalid parameters.
Sep 01 10:06:40 ivy1 node[3743]:     at RequestManager.handleResponse (/usr/bin/sashimono/reputationd/index.js:59:91027)
Sep 01 10:06:40 ivy1 node[3743]:     at Connection.onMessage (/usr/bin/sashimono/reputationd/index.js:59:96558)
Sep 01 10:06:40 ivy1 node[3743]:     at WebSocket.<anonymous> (/usr/bin/sashimono/reputationd/index.js:59:97000)
Sep 01 10:06:40 ivy1 node[3743]:     at WebSocket.emit (node:events:519:28)
Sep 01 10:06:40 ivy1 node[3743]:     at Receiver.receiverOnMessage (/usr/bin/sashimono/reputationd/index.js:59:75763)
Sep 01 10:06:40 ivy1 node[3743]:     at Receiver.emit (node:events:519:28)
Sep 01 10:06:40 ivy1 node[3743]:     at Receiver.dataMessage (/usr/bin/sashimono/reputationd/index.js:59:46441)
Sep 01 10:06:40 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:45652
Sep 01 10:06:40 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:37708
Sep 01 10:06:40 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:38659 {
Sep 01 10:06:40 ivy1 node[3743]:   data: {
Sep 01 10:06:40 ivy1 node[3743]:     error: 'invalidParams',
Sep 01 10:06:40 ivy1 node[3743]:     error_code: 31,
Sep 01 10:06:40 ivy1 node[3743]:     error_message: 'Invalid parameters.',
Sep 01 10:06:40 ivy1 node[3743]:     id: 1225,
Sep 01 10:06:40 ivy1 node[3743]:     request: {
Sep 01 10:06:40 ivy1 node[3743]:       account: 'raYDnpvfRTtAQhi9BeidowAcU8NtcFVbvt',
Sep 01 10:06:40 ivy1 node[3743]:       command: 'account_lines',
Sep 01 10:06:40 ivy1 node[3743]:       id: 1225,
Sep 01 10:06:40 ivy1 node[3743]:       ledger_index: 'validated',
Sep 01 10:06:40 ivy1 node[3743]:       limit: 400,
Sep 01 10:06:40 ivy1 node[3743]:       marker: '379DD0DB375CA48E55281FDCB9B7C40A7FF9CD53B50CE94AF087634B978C5C54,276',
Sep 01 10:06:40 ivy1 node[3743]:       peer: 'rEvernodee8dJLaFsujS6q1EiXvZYmHXr8'
Sep 01 10:06:40 ivy1 node[3743]:     },
Sep 01 10:06:40 ivy1 node[3743]:     status: 'error',
Sep 01 10:06:40 ivy1 node[3743]:     type: 'response'
Sep 01 10:06:40 ivy1 node[3743]:   }
Sep 01 10:06:40 ivy1 node[3743]: }
Sep 01 10:06:40 ivy1 node[3743]: 20240901 15:06:40 [dbg] Retry attempt 2
Sep 01 10:11:40 ivy1 node[3743]: 20240901 15:11:40 [err] RippledError: Invalid parameters.
Sep 01 10:11:40 ivy1 node[3743]:     at RequestManager.handleResponse (/usr/bin/sashimono/reputationd/index.js:59:91027)
Sep 01 10:11:40 ivy1 node[3743]:     at Connection.onMessage (/usr/bin/sashimono/reputationd/index.js:59:96558)
Sep 01 10:11:40 ivy1 node[3743]:     at WebSocket.<anonymous> (/usr/bin/sashimono/reputationd/index.js:59:97000)
Sep 01 10:11:40 ivy1 node[3743]:     at WebSocket.emit (node:events:519:28)
Sep 01 10:11:40 ivy1 node[3743]:     at Receiver.receiverOnMessage (/usr/bin/sashimono/reputationd/index.js:59:75763)
Sep 01 10:11:40 ivy1 node[3743]:     at Receiver.emit (node:events:519:28)
Sep 01 10:11:40 ivy1 node[3743]:     at Receiver.dataMessage (/usr/bin/sashimono/reputationd/index.js:59:46441)
Sep 01 10:11:40 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:45652
Sep 01 10:11:40 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:37708
Sep 01 10:11:40 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:38659 {
Sep 01 10:11:40 ivy1 node[3743]:   data: {
Sep 01 10:11:40 ivy1 node[3743]:     error: 'invalidParams',
Sep 01 10:11:40 ivy1 node[3743]:     error_code: 31,
Sep 01 10:11:40 ivy1 node[3743]:     error_message: 'Invalid parameters.',
Sep 01 10:11:40 ivy1 node[3743]:     id: 1246,
Sep 01 10:11:40 ivy1 node[3743]:     request: {
Sep 01 10:11:40 ivy1 node[3743]:       account: 'raYDnpvfRTtAQhi9BeidowAcU8NtcFVbvt',
Sep 01 10:11:40 ivy1 node[3743]:       command: 'account_lines',
Sep 01 10:11:40 ivy1 node[3743]:       id: 1246,
Sep 01 10:11:40 ivy1 node[3743]:       ledger_index: 'validated',
Sep 01 10:11:40 ivy1 node[3743]:       limit: 400,
Sep 01 10:11:40 ivy1 node[3743]:       marker: '379DD0DB375CA48E55281FDCB9B7C40A7FF9CD53B50CE94AF087634B978C5C54,276',
Sep 01 10:11:40 ivy1 node[3743]:       peer: 'rEvernodee8dJLaFsujS6q1EiXvZYmHXr8'
Sep 01 10:11:40 ivy1 node[3743]:     },
Sep 01 10:11:40 ivy1 node[3743]:     status: 'error',
Sep 01 10:11:40 ivy1 node[3743]:     type: 'response'
Sep 01 10:11:40 ivy1 node[3743]:   }
Sep 01 10:11:40 ivy1 node[3743]: }
Sep 01 10:11:40 ivy1 node[3743]: 20240901 15:11:40 [dbg] Retry attempt 3
Sep 01 10:16:27 ivy1 node[3743]: 20240901 15:16:27 [dbg] Skipping reputation contract preparation since there's no universe info for the moment 6298.
Sep 01 10:16:41 ivy1 node[3743]: 20240901 15:16:41 [err] RippledError: Invalid parameters.
Sep 01 10:16:41 ivy1 node[3743]:     at RequestManager.handleResponse (/usr/bin/sashimono/reputationd/index.js:59:91027)
Sep 01 10:16:41 ivy1 node[3743]:     at Connection.onMessage (/usr/bin/sashimono/reputationd/index.js:59:96558)
Sep 01 10:16:41 ivy1 node[3743]:     at WebSocket.<anonymous> (/usr/bin/sashimono/reputationd/index.js:59:97000)
Sep 01 10:16:41 ivy1 node[3743]:     at WebSocket.emit (node:events:519:28)
Sep 01 10:16:41 ivy1 node[3743]:     at Receiver.receiverOnMessage (/usr/bin/sashimono/reputationd/index.js:59:75763)
Sep 01 10:16:41 ivy1 node[3743]:     at Receiver.emit (node:events:519:28)
Sep 01 10:16:41 ivy1 node[3743]:     at Receiver.dataMessage (/usr/bin/sashimono/reputationd/index.js:59:46441)
Sep 01 10:16:41 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:45652
Sep 01 10:16:41 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:37708
Sep 01 10:16:41 ivy1 node[3743]:     at /usr/bin/sashimono/reputationd/index.js:59:38659 {
Sep 01 10:16:41 ivy1 node[3743]:   data: {
Sep 01 10:16:41 ivy1 node[3743]:     error: 'invalidParams',
Sep 01 10:16:41 ivy1 node[3743]:     error_code: 31,
Sep 01 10:16:41 ivy1 node[3743]:     error_message: 'Invalid parameters.',
Sep 01 10:16:41 ivy1 node[3743]:     id: 1268,
Sep 01 10:16:41 ivy1 node[3743]:     request: {
Sep 01 10:16:41 ivy1 node[3743]:       account: 'raYDnpvfRTtAQhi9BeidowAcU8NtcFVbvt',
Sep 01 10:16:41 ivy1 node[3743]:       command: 'account_lines',
Sep 01 10:16:41 ivy1 node[3743]:       id: 1268,
Sep 01 10:16:41 ivy1 node[3743]:       ledger_index: 'validated',
Sep 01 10:16:41 ivy1 node[3743]:       limit: 400,
Sep 01 10:16:41 ivy1 node[3743]:       marker: '379DD0DB375CA48E55281FDCB9B7C40A7FF9CD53B50CE94AF087634B978C5C54,276',
Sep 01 10:16:41 ivy1 node[3743]:       peer: 'rEvernodee8dJLaFsujS6q1EiXvZYmHXr8'
Sep 01 10:16:41 ivy1 node[3743]:     },
Sep 01 10:16:41 ivy1 node[3743]:     status: 'error',
Sep 01 10:16:41 ivy1 node[3743]:     type: 'response'
Sep 01 10:16:41 ivy1 node[3743]:   }
Sep 01 10:16:41 ivy1 node[3743]: }
Sep 01 10:16:41 ivy1 node[3743]: 20240901 15:16:41 [err] Max retry attempts reached. Abandoned.

**Comment by du1ana** [comment]
hi, please run the following commands and send the outputs you get:

MB-XRPL log : 
`sudo -u sashimbxrpl bash -c journalctl --user -u sashimono-mb-xrpl | tail -n 250`

Reputationd status : 
`evernode reputationd status`


Also please send your Evernode log. Run `evernode log` and your saved log file path will be displayed. You can use `cat <log file path>` to retrieve it.
